input {
  file {
    path => "/usr/share/logstash/external_logs/audit.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "jarl-audit-logs"
  }
  stdout {
    codec => rubydebug
  }
}
